### ISSUE TITLE
MPV 

### ISSUE THREAD

**Issue by couleurm** [Killerjet101/replugged-OpenInApp#6]
Hey, you can make URLs link to different protocols if you put a < and > at the start and end of them, and I've been using this to make links that open videos directly in MPV, this registry key works great (though not penguin friendly):
![image](https://user-images.githubusercontent.com/82747632/181584742-af68b32e-9e99-4398-8374-1c62f5e6a873.png)
Would be cool if you could add an option to have a custom command ran with `%1` as the URL when clicking on a link on discord that ends with .mp4, .mkv, .webm..

**Comment by lorencerri** [comment]
I don't believe Powercord is maintained anymore, sorry!

**Comment by couleurm** [comment]
well maybe GooseMod can :)

**Comment by Killerjet101** [comment]
I do plan on moving my plugins over to BetterDiscord and GooseMod within the next few weeks. And I'll see what I can do about the feature request!

**Comment by Killerjet101** [comment]
I also plan on moving the plugins to the continued Replugged client if people still want the plugins. But we shall see.

**Comment by Killerjet101** [comment]
Yeah, Powercord is dead now. Plugins were working on Replugged (new Powercord) but Discord did an update and broke them so right now they are going through a rewrite. Also means I would have to rewrite the plugin but for now, I would like to wait until it's no longer a dev build of the client. GooseMod I could port over but not sure if many people use that and I will be planning on porting this plugin to BetterDiscord since that's the platform I plan to switch to. Also, some people on BetterDiscord have been porting plugins and not giving credit so I would like to beat them to the punch and make it official from me. But that's my update for this and the rest of my plugins. Sorry for the bad news. For now, the plugins will stay archived but if someone would like to help port them to Replugged when they update or on the dev build or move it to GooseMod and help maintain it then just contact me on Discord (Jet#2471)
